apps/principal/urls.py
# Python imports


# Django imports
from django.conf.urls import url


# Local imports
from .views import (
    GrupoView,
    IndexView,
    OficinasView,
    TramitesView,
    TramiteView,
)

# Create your tests here.


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='principal'),
    url(r'^grupo/$', GrupoView.as_view(), name='grupo'),
    url(r'^oficinas/$', OficinasView.as_view(), name='oficinas'),
    url(r'^tramites/$', TramitesView.as_view(), name='tramites'),
    url(r'^tramites/(?P<id>\d+)/$', TramiteView.as_view(), name='tramite'),
]

proyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from apps.principal import urls as principal_urls

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(principal_urls, namespace='principal')),
]

apps/principal/models.py
# Python imports


# Django imports
from django.db import models


# Local imports


# Create your models here.
class Oficinas(models.Model):
    nombre = models.CharField(
        max_length=100,
        verbose_name="Nombre de la oficina"
        )

    class Meta:
        verbose_name = "Oficina"

    def __str__(self):
        return self.nombre


class Tramites(models.Model):
    oficinas = models.ManyToManyField(Oficinas)
    nombre = models.CharField(
        max_length=100,
        verbose_name='Nombre del trámite'
        )
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaModificacion = models.DateTimeField(auto_now=True)
    descripcion = models.TextField(verbose_name="Descripción del trámite")

    class Meta:
        verbose_name = "Trámite"
        verbose_name_plural = "Trámites"

    def __str__(self):
        return self.nombre

apps/principal/forms.py
# Python imports


# Django imports
from django import forms


# Local imports


# Create your models here.

apps/principal/views.py
# Python imports


# Django imports
from django.views.generic.base import TemplateView


# Local imports
from .models import Oficinas, Tramites


# Create your views here.
class IndexView(TemplateView):
    template_name = 'principal/index.html'


class GrupoView(TemplateView):
    template_name = 'principal/grupo.html'


class OficinasView(TemplateView):
    template_name = 'principal/oficinas.html'

    def get_context_data(self, **kwargs):
        oficinas = Oficinas.objects.all()
        contexto = {'oficinas': oficinas}
        return contexto


class TramitesView(TemplateView):
    template_name = 'principal/tramites.html'

    def get_context_data(self, **kwargs):
        tramites = Tramites.objects.all()
        contexto = {'tramites': tramites}
        return contexto


class TramiteView(TemplateView):
    template_name = 'principal/tramite.html'

    def get_context_data(self, **kwargs):
        tramite = Tramites.objects.get(id=self.kwargs['id'])
        contexto = {'tramite': tramite}
        return contexto

apps/principal/templates/principal/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <title>Primera-Web</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'scripts/bootstrap.min.js' %}"></script>
    <script>
(function ($) {
  // custom css expression for a case-insensitive contains()
  jQuery.expr[':'].Contains = function(a,i,m){
      return (a.textContent || a.innerText || "").toUpperCase().indexOf(m[3].toUpperCase())>=0;
  };

  function filterList(header, list) {
  // header is any element, list is an unordered list
    // create and add the filter form to the header
    var form = $("<form>").attr({"class":"filterform","action":"#"}),
        input = $("<input>").attr({"class":"filterinput","type":"text"});
    $(form).append(input).appendTo(header);

    $(input)
      .change( function () {
        var filter = $(this).val();
        if(filter) {

      $matches = $(list).find('a:Contains(' + filter + ')').parent();
      $('li', list).not($matches).slideUp();
      $matches.slideDown();

        } else {
          $(list).find("li").slideDown();
        }
        return false;
      })
    .keyup( function () {
        // fire the above change event after every letter
        $(this).change();
    });
  }
  //ondomready
  $(function () {
    filterList($("#form"), $("#list"));
  });
}(jQuery));
  </script>
</head>
<body style="brackground-color:black">
    <!-- Inicio cabezera -->
   <div class="pre-header">
       <div id="fisi">
           <a href="http://sistemas.edu.pe/">
               <img src="{% static 'images/fisi.png' %}" alt="">
           </a>
       </div>

   </div>
    <!-- FIN cabezera -->
    <center><img src="{% static 'images/logo_fisi.png' %}" alt=""></center>
    <center><h1>Sistema automatico de información de tramite</h1></center>


    {% block navegador %}{% endblock %}

    <!-- Inicio Cuerpo -->
    <header>
    <div class="col-md-2"></div>
    <div class="col-md-8">
        {% block cuerpo %}{% endblock %}
    </div>
    <div class="col-md-2"></div>
    </header>
    
    <!-- fin Cuerpo -->

    <!-- inicio footer-->
    <footer>
        <div class="col-md-2"> </div>
        <div class="col-md-8">
            <div id="lafacultad">
                <h4>LA FACULTAD</h4>
                <a href="http://sistemas.edu.pe/software/">EAP Ingeniería de Software</a><br>
                <a href="http://sistemas.edu.pe/sistemas/">EAP Ingeniería de Sistemas</a><br>
                <a href="http://sistemas.edu.pe/posgrado/">Posgrado</a><br>
                <a href="http://sistemas.edu.pe/ceups">CEUPS</a><br>
                <a href="http://sistemas.edu.pe/unidad/occa">OCCA</a>
            </div>

            <div id="serviciosuniversitarios">
                <h4>SERVICIOS UNIVERSITARIOS</h4>
                <a href="http://sisbib.unmsm.edu.pe/">Sistemas de Bibliotecas</a><br>
                <a href="http://unmsm.edu.pe/occaa/">Calidad Academica OCCA</a><br>
                <a href="http://ccsm-unmsm.edu.pe/">Centro Cultural</a><br>
                <a href="http://clinica.unmsm.edu.pe/clinica/">Clinica Universitaria</a><br>
                <a href="http://ogbu.unmsm.edu.pe/">Bolsa de Trabajo</a>
            </div>
            <div id="Servicioalestudiante">
                <h4>SERVICIO AL ESTUDIANTE</h4>
                <a href="http://sistemas.edu.pe/unidad/unayoe">UNAYOE</a><br>
                <a href="http://sistemas.edu.pe/bolsa-de-trabajo">Bolsa de Trabajo</a><br>
                <a href="http://sistemas.edu.pe/biblioteca/">Biblioteca</a><br>
                <a href="http://sistemas.edu.pe/unidad/bienstar">Unidad de Bienestar</a>

            </div>

        </div>
        <div class="col-md-2"></div>
    </footer>
    <!-- fin navegador -->

</body>
</html>

apps/principal/templates/principal/grupo.html
{% extends "principal/base.html" %}

{% block navegador %}
<nav>
  <ul class="nav nav-pills" >
    <li role="presentation"><a href="{% url 'principal:principal' %}">Inicio</a></li>
    <li role="presentation"><a href="{% url 'principal:oficinas' %}"> Oficinas</a></li>
    <li role="presentation"><a href="{% url 'principal:tramites' %}">Tramites</a></li>
    <li role="presentation" class="active"><a href="{% url 'principal:grupo' %}">Grupo</a></li>
  </ul>
</nav>
<div class="col-md-2"></div>
<div class="col-md-8">
    <h4>Grupo OLIMPO conformado por: </h4>
    <ul>
        <li>Deza Culque, Edwin Junior</li>
        <li>Zea Guerrero, Jose Miguel</li>
        <li>Santos Rodriguez, Ronald</li>
    
    </ul>
    
</div>
<div class="col-md-2"></div>

{% endblock %}

apps/principal/templates/principal/index.html
{% extends "principal/base.html" %}

{% block navegador %}

<nav>
  <ul class="nav nav-pills" >
    <li role="presentation" class="active"><a href="{% url 'principal:principal' %}">Inicio</a></li>
    <li role="presentation"><a href="{% url 'principal:oficinas' %}"> Oficinas</a></li>
    <li role="presentation"><a href="{% url 'principal:tramites' %}">Tramites</a></li>
    <li role="presentation"><a href="{% url 'principal:grupo' %}">Grupo</a></li>
  </ul>
</nav>

{% endblock %}


{% block cuerpo %}
  
<h4>Pagina Diseñada por Alumnos de la Escuela de Software de la Facultad de Ingerniería de Sistemas e Informatica</h4>


<h5>La intención de este primera avanze es que en otra ocacion otro grupo puedo terminar la gran labor presente aquí para poder solucionar la necesidad de la facultad expuesta por nuestros compañeros</h5>

{% endblock %}

apps/principal/templates/principal/oficinas.html
{% extends "principal/base.html" %}

{% block navegador %}
<nav>
  <ul class="nav nav-pills" >
    <li role="presentation"><a href="{% url 'principal:principal' %}">Inicio</a></li>
    <li role="presentation" class="active"><a href="{% url 'principal:oficinas' %}"> Oficinas</a></li>
    <li role="presentation"><a href="{% url 'principal:tramites' %}">Tramites</a></li>
    <li role="presentation"><a href="{% url 'principal:grupo' %}">Grupo</a></li>
  </ul>
</nav>
<br>
<br>
{% endblock %}





{% block cuerpo %}
  <ul>
  {% for oficina in oficinas %}
    <li>{{ oficina }}</li>
  {% endfor %}
  </ul>
{% endblock %}

apps/principal/templates/principal/tramite.html
{% extends "principal/tramites.html" %}



//Detalles del tramite.

{% block cuerpo %} 
<br>
<br>
<ul>
  <li>Nombre del Trámite: {{ tramite.nombre }}</li>
  <li>Oficinas por donde pasa:
    <ul>
      {% for oficina in tramite.oficinas.all %}
        <li>{{ oficina }}</li>
      {% endfor %}
    </ul>
  </li>
  <li>Descipción del trámite: {{ tramite.descripcion }}</li>
  <li>Fecha de ultima Actualización: {{ tramite.fechaModificacion }}</li>
</ul>
{% endblock %}

apps/principal/templates/principal/tramites.html
{% extends "principal/base.html" %}

{% block navegador %}
<nav>
  <ul class="nav nav-pills" >
    <li role="presentation"><a href="{% url 'principal:principal' %}">Inicio</a></li>
    <li role="presentation"><a href="{% url 'principal:oficinas' %}"> Oficinas</a></li>
    <li role="presentation" class="active"><a href="{% url 'principal:tramites' %}">Tramites</a></li>
    <li role="presentation"><a href="{% url 'principal:grupo' %}">Grupo</a></li>
  </ul>
</nav>
{% endblock %}





{% block cuerpo %}
<h2>Buscador de Trámites</h2>
<h4>Introdusca el nombre del tramite buscado en el filtro:</h4>
<div id="form"></div>
<div class="clear"></div>    
<ul id="list">
  {% for tramite in tramites %}
    <li><a href="{% url 'principal:tramite' tramite.id %}">{{ tramite.nombre }}</a></li>
  {% endfor %}
</ul>
{% endblock %}